FROM shlo/smart-pillbox:deps.arm32v7

WORKDIR /app

#COPY requirements.txt ./
#RUN pip install -r requirements.txt

COPY . .

ENTRYPOINT ["bash", "init.sh"]

# sudo docker run --privileged=true --device /dev/vchiq --device /dev/snd