FROM arm32v7/python:3.10-bullseye

RUN apt-get update && apt-get install -y \
    vim \
    git

RUN pip install --no-cache-dir \
    azure-iot-device \
    azure-cosmos \
    tzupdate \
    schedule

WORKDIR /app

COPY . .

ENTRYPOINT ["bash", "init.debug.sh"]